version: '3.9'
services:
  user:
    container_name: user
    build: ./user
    ports:
      - "5000:5000"
    environment:
      - OTEL_TRACES_EXPORTER=jaeger_thrift
      - OTEL_METRICS_EXPORTER:none 
      - OTEL_SERVICE_NAME=user-service
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces

  todo:
    container_name: todo
    build: ./todo
    ports:
      - "5001:5000"
    environment:
      - OTEL_TRACES_EXPORTER=jaeger_thrift
      - OTEL_METRICS_EXPORTER:none 
      - OTEL_SERVICE_NAME=todo-service
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - PYTHONUNBUFFERED=1
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411